[real_ip]
x_for = 1
ipv4_prefix = 32
ipv6_prefix = 56

[botdetection.ip_limit]
filter_link_local = true
link_token = true

[botdetection.ip_lists]
block_ip = []
pass_ip = []

[botdetection.rate_limit]
enabled = true
burst = 240
rate = 20